
#### 회원 부분

### 회원 리스트 테스트(성공)
GET http://localhost:8080/admin/member/list


### 회원 역할 변경 테스트(성공)
POST http://localhost:8080/admin/member/role
Content-Type: application/json

{
  "email" : "danaver12@daum.net",
  "role" : "USER"
}

### 회원 상태 변경 테스트(성공)
POST http://localhost:8080/admin/member/status
Content-Type: application/json

{
  "email": "danaver12@daum.net",
  "userStatus" : "USING"
}

### 회원 상세정보 테스트(성공)
GET http://localhost:8080/admin/member/detail?email=danaver12daum.net

### 회원 비밀번호 변경(성공)
POST http://localhost:8080/admin/member/password
Content-Type: application/json

{
  "email": "danaver12@daum.net",
  "password": "ehdrmsehdrms"
}



### 카테고리 부분

### 관리자 카테고리 검색(성공)
GET http://localhost:8080/admin/category/list

### 관리자 카테고리 추가(성공)
POST http://localhost:8080/admin/category/add?categoryName=서적


### 관리자 카테고리 삭제(성공)
DELETE http://localhost:8080/admin/category/remove/1

<> 2022-12-26T121350.200.json

### 관리자 카테고리 수정(성공)
PUT http://localhost:8080/admin/category/update
Content-Type: application/json

{
  "id" : 3,
  "categoryName" : "문구",
  "sortValue" : 5,
  "usingYn": true
}






#### 상품 부분

### 관리자 상품 검색(성공)
GET http://localhost:8080/admin/product/list

### 관리자 상품 등록(성공)
POST http://localhost:8080/admin/product/add
Content-Type: application/json

{
  "productName" : "자바 프로그래밍2",
  "price" : 8000,
  "salePrice" : 8000,
  "categoryId" : 7,
  "productStatus": "USED",
  "stock" : 1
}

### 관리자 상품 삭제(성공)
POST http://localhost:8080/admin/product/remove
Content-Type: application/json

{
  "id" : 2,
  "productName" : "아이폰12"
}

### 관리자 상품 수정(성공)
PUT http://localhost:8080/admin/product/update/1
Content-Type: application/json

{
"productName" : "아이폰11S",
"productSaleStatus" : "ON_SALE",
"productStatus" : "NEW",
"price" : 10000,
"salePrice" : 8000,
"stock" : 2
}


