
#### 회원 부분

### 회원 리스트 테스트(성공)
GET http://localhost:8080/admin/member/list


### 회원 역할 변경 테스트(성공)
POST http://localhost:8080/admin/member/role
Content-Type: application/json

{
  "email" : "danaver12@daum.net",
  "role" : "USER"
}

### 회원 상태 변경 테스트(성공)
POST http://localhost:8080/admin/member/status
Content-Type: application/json

{
  "email": "danaver12@daum.net",
  "userStatus" : "USING"
}


### 회원 상세정보 테스트(성공)
GET http://localhost:8080/admin/member/detail?email=danaver12daum.net

### 회원 비밀번호 변경(성공)
POST http://localhost:8080/admin/member/password
Content-Type: application/json

{
  "email": "danaver12@daum.net",
  "password": "ehdrmsehdrms"
}



### 관리자 상품 검색(성공)
GET http://localhost:8080/admin/product/list

### 관리자 상품 등록(성공)
POST http://localhost:8080/admin/product/add
Content-Type: application/json

{
  "productName" : "아이폰12",
  "price" : 1200000,
  "salePrice" : 1000000,
  "productStatus": "USED",
  "stock" : 1
}

### 관리자 상품 삭제(성공)
POST http://localhost:8080/admin/product/remove
Content-Type: application/json

{
  "id" : 2,
  "productName" : "아이폰12"
}



