
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    driver-class-name: org.mariadb.jdbc.Driver
    username: choidongkuen
    password: ehdrms6390

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: danaver13@gmail.com
    password: hhzdfiabtszbaqvq
    properties:
      mail:
        smtp:
          starttls:
            enable: true


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl